// frontend-react/todoism/src/components/Task.js
import { useRef, useEffect } from 'react'

function Task({index, task: { taskTitle, taskDescription, priority, dueDate, isComplete}}) {

  const taskDetailsRef = useRef()
  const priorityLabelRef = useRef()
  const taskWrapperRef = useRef()
  const moreMenuRef = useRef()

  function getPriorityClasses(priority) {
    let wrapper = ''
    let label = ''

    if (priority === 'Default') {
      wrapper = 'priority-default-border'
      label = 'bg-light'
    } else if (priority === 'High') {
      wrapper = 'priority-high-border'
      label = 'bg-danger'
    } else if (priority === 'Low') {
      wrapper = 'priority-low-border'
      label = 'bg-low'
    } else if (priority === 'Medium') {
      wrapper = 'priority-medium-border'
      label = 'bg-medium'
    }

    return { wrapperClassName: wrapper, labelBackgroundClassName: label }
  }

  useEffect(() => {
    let { wrapperClassName, labelBackgroundClassName } = getPriorityClasses(priority)
    taskWrapperRef.current.classList.add(wrapperClassName)
    priorityLabelRef.current.classList.add(labelBackgroundClassName)
  }, [])

  function handleShowTaskClick(e) {
    console.log(index)
    const button = e.target
    button.classList.toggle('fa-chevron-down')
    button.classList.toggle('fa-chevron-up')
    taskDetailsRef.current.classList.toggle('hide')
  }

  function showTaskDetails() {
    taskDetailsRef.current.classList.remove('hide')
  }

  function handleCheckboxClick(e) {
    isComplete = !isComplete
  }

  function handleShowMoreClick() {
    moreMenuRef.current.classList.toggle('hide')
  }

  return (
    <div className="task" data-index="0" ref={taskWrapperRef}>
      <div className="task-content">
        <input type="checkbox" id={'task-' + index} defaultChecked={isComplete} onChange={handleCheckboxClick}/>
        <div className="checkbox-wrapper">
          <label htmlFor={'task-' + index}>
            <span className="checkbox">
              <span className="check"></span>
            </span>
          </label>
        </div>
        <div className="task-text">
          <div className="title">{taskTitle}</div>
          <div className="task-details hide" ref={taskDetailsRef}>
            <div className="description font-sm">
              {taskDescription}
            </div>
            <div className="flex-row">
              <div className="priority font-sm" ref={priorityLabelRef}>{priority}</div>
              <div className="due-date font-sm">
                Due date
                <span className="date"> {dueDate} </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="task-menu">
        <i className="fas fa-chevron-down icon chevron" onClick={handleShowTaskClick}></i>
        <i className="fas fa-ellipsis-v icon more" onClick={handleShowMoreClick}></i>
        <div className="more-menu hide" ref={moreMenuRef}>
          <ul>
            <li className="more-menu-option edit">
              <i className="far fa-edit icon"></i>Edit
            </li>
            <li className="more-menu-option delete">
              <i className="far fa-trash-alt icon"></i> Delete
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Task;

// front-svelte/src/Task.svelte
<script>
	import { TaskPriority } from './TaskPriority';
	import { createEventDispatcher } from 'svelte';
	import AppConfig from './AppConfig';
	import { postRequest } from './HttpUtils';

	let dispatch = createEventDispatcher();

	export let index;
	export let task;
	export let projectId;
	let taskDetails;

	function handleCheckTask(taskId) {
		let url = `${AppConfig.API_URL}/project/${projectId}/task/${taskId}/togglecomplete`;
		console.log(url);
		postRequest(url, taskId);
		dispatch('update', { id: taskId });
	}

	function getPriorityPrettyName(priority) {
		if (priority === TaskPriority.DEFALUT_PRIORITY) {
			return 'Default';
		} else if (priority === TaskPriority.LOW_PRIORITY) {
			return 'Low';
		} else if (priority === TaskPriority.MEDIUM_PRIORITY) {
			return 'Medium';
		} else if (priority === TaskPriority.HIGH_PRIORITY) {
			return 'High';
		}
	}

	function getPriorityClassForWrapper(priorityFromDB) {
		if (priorityFromDB === TaskPriority.DEFALUT_PRIORITY) {
			return '';
		} else if (priorityFromDB === TaskPriority.LOW_PRIORITY) {
			return 'priority-low-border';
		} else if (priorityFromDB === TaskPriority.MEDIUM_PRIORITY) {
			return 'priority-medium-border';
		} else if (priorityFromDB === TaskPriority.HIGH_PRIORITY) {
			return 'priority-high-border';
		}
	}

	function getPriorityClassForLabel(priority) {
		if (priority === TaskPriority.DEFALUT_PRIORITY) {
			return 'bg-default';
		} else if (priority === TaskPriority.LOW_PRIORITY) {
			return 'bg-low';
		} else if (priority === TaskPriority.MEDIUM_PRIORITY) {
			return 'bg-medium';
		} else if (priority === TaskPriority.HIGH_PRIORITY) {
			return 'bg-danger';
		}
	}

	function getPrettyDate(timestamp) {
		return new Date(timestamp);
	}

	function handleExpandTaskClick(taskToExpand) {
		task.isExpanded = !task.isExpanded;
	}

	function handleShowTaskMenu(clickedTask) {
		let taskListCopy = [...taskList];
		taskListCopy.forEach((task) => {
			if (task === clickedTask) {
				task.showMenu = !task.showMenu;
			}
		});
		taskList = taskListCopy;
	}

  function handleDeleteTask(taskId) {
    dispatch('delete', {id: taskId});
  }
</script>

<div class="task {getPriorityClassForWrapper(task.priority)}" data-index={index}>
	<div class="task-content">
		<input
			type="checkbox"
			id="task-{index}"
			checked={task.completed}
			on:click={handleCheckTask(task.taskId)}
		/>
		<div class="checkbox-wrapper">
			<label for="task-{index}">
				<span class="checkbox">
					<span class="check"></span>
				</span>
			</label>
		</div>
		<div class="task-text">
			<div class="title">{task.title}</div>
			<div class="task-details {task.isExpanded ? '' : 'hide'}" bind:this={taskDetails}>
				<div class="description font-sm">
					{task.description}
				</div>
				<div class="flex-row">
					<div class="priority {getPriorityClassForLabel(task.priority)} font-sm">
						{getPriorityPrettyName(task.priority)}
					</div>
					<div class="due-date font-sm">
						Due date
						<span class="date"> {getPrettyDate(task.dueDate)} </span>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="task-menu">
		<li class="more-menu-option edit">
			<i class="far fa-edit icon"></i>
		</li>
		<li class="more-menu-option delete" on:click={handleDeleteTask(task.taskId)}>
			<i class="far fa-trash-alt icon"></i>
		</li>
		<i
			class="fas {task.isExpanded ? 'fa-chevron-up' : 'fa-chevron-down'} icon chevron"
			on:click={handleExpandTaskClick(task)}
		></i>
		<i class="fas fa-ellipsis-v icon more hide" on:click={handleShowTaskMenu(task)}></i>
		<div class="more-menu {task.showMenu ? '' : 'hide'}">
			<ul></ul>
		</div>
	</div>
</div>
